version: 2.1

default: &default_env
  docker:
    - image: circleci/node:13.8.0

command:
  npm_init:
    steps:
      - run: checkout
      - run: npm i

jobs:
  build:
    <<: *default_env
    steps:
      - npm_init
      - save_cache:
          key: "npm-packages"
          paths:
            - ./node_modules
      - run: npm run build

  test:
    <<: *default_env
    steps:
      - restore_cache:
          key: "npm-packages"
      - npm_init
      - run: npm run test

  analyze:
    <<: *default_env
    steps:
      - run: checkout
      - run: npm audit

workflows:
  react-slingshot:
    jobs:
    - build
    - test:
        requires: [build]
    - analyze:
        requires: [test]